name: Build and Release

on: push

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run bundle

      - name: Set Git User
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "${{ github.actor }}"

      - name: Check if tag exists
        id: check_tag
        run: |
          version=$(node -e "console.log(require('./package.json').version)")
          tag_exists=$(git ls-remote --tags origin "refs/tags/v$version")
          if [ -z "$tag_exists" ]; then
            echo "Tag does not exist. Creating tag..."
            git tag -a -m "Tag for version $version" "v$version"
            git push origin "v$version"
          else
            echo "Tag v$version already exists."
          fi
        shell: bash

      - name: Create Release
        id: create_release
        run: |
          version=$(node -e "console.log(require('./package.json').version)")
          echo "Creating release for version $version"
          curl \
            -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "{\"tag_name\": \"v$version\", \"name\": \"Release $version\"}" \
            "https://api.github.com/repos/${{ github.repository }}/releases"
        shell: bash

      - name: Upload Artifacts
        run: |
          version=$(node -e "console.log(require('./package.json').version)")
          echo "Uploading artifacts for version $version"
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            artifact_file="haax-dbc.exe"
          else
            artifact_file="haax-dbc"
          fi
          ls
          curl \
            -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/octet-stream" \
            --data-binary @"$artifact_file" \
            "https://uploads.github.com/repos/${{ github.repository }}/releases/${{ steps.create_release.outputs.id }}/assets?name=$artifact_file"
        shell: bash
